spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sspg?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
#配置xml文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql