spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sspg?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
redis:
  host: 127.0.0.1
#  password: redispassword
  port: 6379
  pool:
    max-idle: 100
    min-idle: 1
    max-active: 1000
    max-wait: -1
#配置xml文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
#pagehelper分页插件:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql